[build]
installCmd = "yarn workspaces focus twenty-server --production"
buildCmd = "yarn build"
startCmd = "yarn start"

cacheDirs = [
  "../../.yarn/cache",
  "../../.yarn/install-state.gz",
  "../../.yarn/unplugged",
  "node_modules"
]
